### ISSUE TITLE
Bootstrap takes 60 seconds to run even when nothing has changed

### ISSUE THREAD

**Issue by edmorley** [guigrpa/oao#42] opened 2017-06-12 22:43 UTC
**STR:**
1. Install nodejs 8.1.0 and yarn v0.24.6 under Ubuntu 16.04.
2. `git clone https://github.com/mozilla-neutrino/neutrino-dev`
3. `cd neutrino-dev && git checkout 13adea32550de2f1eae9ae79f2980f8a2f6b5e82`
4. `yarn install` (this installs oao v0.8.0)
5. `yarn bootstrap` (which runs `oao bootstrap` from the local `node_modules`)
6. `yarn bootstrap`

**Expected:**
The second time bootstrap is run, the duration is significantly less than the first, ideally <5-10s.

**Actual:**
The first bootstrap took 125 seconds (see https://emorley.pastebin.mozilla.org/9024429), the second still took 63 seconds (see https://emorley.pastebin.mozilla.org/9024430), even though it had nothing to do.

This also affects us on Travis, since it means caching the sub-package's node_modules gives little time saving (and in fact quite a disadvantage, given travis-ci/travis-ci#7898) - see mozilla-neutrino/neutrino-dev#248.

Do you have any ideas as to what might be causing this?

Many thanks!

**Comment by guigrpa** [comment] 2017-06-13 06:22
Thanks for your report!

I'm not sure what's causing the long intervals in your case. I'm on OS X and `oao bootstrap` runs really fast on the monorepos I used it on (admittedly a bit smaller than Neutrino). Maybe yarn is not so optimised for Ubuntu? (it certainly isn't for Windows, for example).

**Could you please check whether it's Phase 1 or Phase 2 of the second `oao bootstrap` that is the main contributor to delay?**

While it won't help you speeding up CI times, you may want to use `oao add/remove/upgrade` to update subpackage dependencies, instead of a full `oao bootstrap`.

**Comment by edmorley** [comment] 2017-06-13 11:23
Hi, thank you for the quick reply!

> I'm on OS X and oao bootstrap runs really fast on the monorepos I used it on (admittedly a bit smaller than Neutrino)

How long do the first/second bootstraps take for Neutrino on your machine, using the STR from above? (So we can rule out platform as an issue)

> Could you please check whether it's Phase 1 or Phase 2 of the second oao bootstrap that is the main contributor to delay?

From the timestamps in the pastebin linked above, it looks like phase 1 is taking 48 seconds and phase 2 is 14 seconds.

Of note for phase 1:
* adding up the total time reported by yarn in the sections of form "Done in 3.12s.", the yarn runtime is 28 seconds, meaning the oao overhead for phase 1 is 20 seconds, which seems quite high.
* the 28 seconds spent in yarn could also likely be reduced, since the log output from yarn for each package never says "success Already up-to-date.", implying that perhaps phase 2 from the prior invocation has invalidated yarns integrity hash. Would reversing the order of phase 1 and 2 help prevent this?

**Comment by guigrpa** [comment] 2017-06-13 12:50
I confirm that I can reproduce your findings on OS X:

* First `yarn bootstrap`: 1:39 (pass 1) + 0:16 (pass 2) = 1:55
* Second `yarn bootstrap`: 0:34 (pass 1) + 0:15 (pass 2) = 0:49
[a third time took 0:38, including ~0:15 again for pass 2]

I did another test replacing all executions of `yarn xxx` (`yarn install` and `yarn link` in this case, to be precise) with `echo Hi`. Total time? < 2 s. Hence, the overhead is not located in `oao`, or even in `shelljs` (which I use to execute commands), but in yarn itself.

Now, I could address some parallelisations, both for Pass 1 and Pass 2, but it may take a little while (a month at most, I guess). Right now I don't have much time… I'll keep you posted!

**Comment by edmorley** [comment] 2017-06-13 13:02
Thank you for looking into this more.

> I did another test replacing all executions of yarn xxx (yarn install and yarn link in this case, to be precise) with echo Hi. Total time? < 2 s. Hence, the overhead is not located in oao, or even in shelljs (which I use to execute commands), but in yarn itself.

Unless the yarn "done in X seconds" output is incorrect, I'm struggling to see where else the time is being spent. The test using `echo` won't have exposed any issues with the stdout/stderr processing performed here for example:
https://github.com/guigrpa/oao/blob/3098ab0586a2ceac6da90612b5765849b433c378/src/utils/shell.js#L67-L74

Perhaps replacing `yarn install/link` with `time yarn install/link` might help confirm whether yarn's self-declared duration is accurate. In addition, it may be worth trying a run with the `child.{stdout,stderr}.pipe(...)` commented out.

**Comment by edmorley** [comment] 2017-06-13 14:05
Profiling using [0x](https://github.com/davidmarkclements/0x) generated this flamegraph:
[flamegraph.html.gz](https://github.com/guigrpa/oao/files/1071620/flamegraph.html.gz)

At first glance I see storyboard taking 23% of the profile, inquirer 14% and `oao/lib/utils/gitjs` 12%.

**Comment by guigrpa** [comment] 2017-06-13 14:26
Indeed, yarn's reported time seems to err on the low side:

```
neutrino-dev $ yarn
yarn install v0.24.5
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.65s.

neutrino-dev $ time yarn
yarn install v0.24.5
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.63s.

real	0m0.821s
user	0m0.832s
sys	0m0.092s
```

**Comment by guigrpa** [comment] 2017-06-15 07:14
If all goes well, `yarn link`s will all run in parallel in the upcoming release. Hopefully this will have a noticeable impact on your build times. I've seen quite an improvement when building my Storyboard monorepo.

**Comment by guigrpa** [comment] 2017-06-15 07:43
`yarn install`s will also run in parallel, except if you explicitly disable it with a `--no-parallel` flag.

**Comment by guigrpa** [comment] 2017-06-15 13:33
Just released v0.8.3:

* `yarn link` now runs always in parallel
* `yarn install` now runs in parallel by default (disable it with `oao bootstrap --no-parallel`)

Perf comparison:

* Neutrino 1st install: from 120 s to **30 s**
* Neutrino 2nd install: from 36-45 s to **10 s**
* Storyboard 2nd install: from 22 s to **5 s**

cc @eliperelman

**Comment by eliperelman** [comment] 2017-06-15 13:34
Wow! 👏 

I'll give this a shot asap!

**Comment by guigrpa** [comment] 2017-06-15 13:35
@eliperelman Btw, I'm also seeing the error reported by @edmorley in https://github.com/mozilla-neutrino/neutrino-dev/issues/251, so it shouldn't be Lerna's fault.

**Comment by eliperelman** [comment] 2017-06-15 14:29
@guigrpa didn't oao used to symlink peerDependencies if they were part of packages?

**Comment by eliperelman** [comment] 2017-06-15 14:33
Ah I see now, for some reason when I ran `oao bootstrap`, all the peerDependencies were removed from my packages' package.jsons.

**Comment by eliperelman** [comment] 2017-06-15 15:09
If there is a failure during the bootstrap process, the package.jsons aren't reverted and end up being replaced with versions that exclude the local peerDependency.

**Comment by eliperelman** [comment] 2017-06-15 15:44
@guigrpa also, if I remove everything:

```bash
rm -rf node_modules yarn.lock packages/*/node_modules packages/*/yarn.lock
```

I constantly fail the bootstrap process, most likely because of some concurrency issue trying to install the same package multiple times with possibly different hashes. These could be related:

https://github.com/yarnpkg/yarn/issues/2629
https://github.com/yarnpkg/yarn/issues/1058
https://github.com/yarnpkg/yarn/issues/1916

**Comment by guigrpa** [comment] 2017-06-15 17:02
Do you believe it is an issue with yarn then?

(If it can be of any help, you can temporarily disable parallelism in the `yarn install`s by running `oao bootstrap --no-parallel` — it will still get you some perf improvements due to parallel `yarn link`s)

**Comment by guigrpa** [comment] 2017-06-15 17:05
In any case, I will investigate why package.jsons are not reverted if an error occurs. In principle, this was handled by the code.

**Comment by eliperelman** [comment] 2017-06-15 20:13
My guess is the problems were caused by too much concurrency and yarn wasn't able to handle it and caused some conflicts. You might be able to replicate by checking out neutrino and removing all node_modules and yarn.locks.

**Comment by guigrpa** [comment] 2017-06-15 21:57
Yes, I've had no problem reproducing it. It happens systematically on Neutrino. Strangely enough, it doesn't happen on [Storyboard](https://github.com/guigrpa/storyboard), which has around 14 subpackages and lots of cross-dependencies.

Regarding the fact that oao didn't recover the original package.jsons, I've found the problem. When one of the branches of the parallel bootstrap failed, the program terminated too soon. I have released a patch (v0.8.4) that waits for all pending promises to resolve before throwing the error.

**Comment by guigrpa** [comment] 2017-06-15 22:01
Have you had a look at yarn's issues with concurrency? Do you think they're widespread? Would you recommend switching parallel bootstrap off (except for `yarn link`s, which have no issues) by default?

**Comment by ericclemmons** [comment] 2017-06-18 18:03
Oh, FYI, I had a similar issue **and the reason is that I had `"postinstall": "oao bootstrap"`.

It was basically cyclical.  What I learned was:

- `oao` should be **global**, not **local**.
- The root should _not_ run `oao bootstrap` at all.

**Comment by guigrpa** [comment] 2017-08-17 15:15
@edmorley @eliperelman oao now has support for [Yarn Workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/); you can try it out in `oao@next` (0.10.0 prereleases). oao detects the workspaces property in the monorepo `package.json` file and automatically uses this feature of Yarn. In this mode:

* `oao bootstrap` just does `yarn install`
* `oao add|remove|upgrade` goes into the particular subpackage folder and runs the corresponding `yarn add|remove|upgrade` command

Note that workspaces are still experimental in yarn (0.28+) and  behind a flag (`yarn config set workspaces-experimental true`). They also may have some limitations wrt. the non-workspace-based behaviour of yarn, so you may want to experiment to see what works better for you.

In principle, this would solve both the performance issue (no overhead wrt. bare-bones yarn) and the concurrency issue described above, so I'm closing this issue. Please send your feedback on the new oao feature!

**Closed by guigrpa** 2017-08-17 15:15 UTC
